events {}

http {
    upstream bluegreen {
        server host.docker.internal:5002;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://bluegreen;
        }
    }
}